required_properties:
  - name
  - bindir
  - etcdir
  - manage_conf
  - contact
  - dist
  - target_arch
  - rpm_group
  - broker_start_runlevels
  - broker_start_order
  - server_start_runlevels
  - server_start_order

artifacts:
 - /usr/src/redhat/**/*.rpm
 - /root/rpmbuild/**/*.rpm
